# This file mounts local docker-entrypoint to use it in agent container.
#
# Use it by exporting
# COMPOSE_FILE=docker-compose.yml:docker/docker-compose.dev.yml and run
# docker-compose as usual.

version: '3'

services:
  agent:
    volumes:
    - ./docker/entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
